"""Configuration file for the scraper"""

STATES = [
    "Andhra Pradesh",
    "Arunachal Pradesh",
    "Assam",
    "Bihar",
    "Chhattisgarh",
    "Goa",
    "Gujarat",
    "Haryana",
    "Himachal Pradesh",
    "Jharkhand",
    "Karnataka",
    "Kerala",
    "Madhya Pradesh",
    "Maharashtra",
    "Manipur",
    "Meghalaya",
    "Mizoram",
    "Nagaland",
    "Odisha",
    "Punjab",
    "Rajasthan",
    "Sikkim",
    "Tamil Nadu",
    "Telangana",
    "Tripura",
    "Uttar Pradesh",
    "Uttarakhand",
    "West Bengal",
    "Andaman and Nicobar Islands",
    "Chandigarh",
    "Dadra and Nagar Haveli and Daman and Diu",
    "Delhi",
    "Jammu and Kashmir",
    "Ladakh",
    "Lakshadweep",
    "Puducherry"
]

# State IDs for different scrapers
BAANKNET_STATE_IDS = {
    "Andaman and Nicobar Islands": "1",
    "Andhra Pradesh": "2",
    "Arunachal Pradesh": "3",
    "Assam": "4",
    "Bihar": "5",
    "Chandigarh": "6",
    "Chhattisgarh": "7",
    "Dadra and Nagar Haveli and Daman and Diu": "8",
    "Delhi": "9",
    "Goa": "10",
    "Gujarat": "11",
    "Haryana": "12",
    "Himachal Pradesh": "13",
    "Jammu and Kashmir": "14",
    "Jharkhand": "15",
    "Karnataka": "16",
    "Kerala": "17",
    "Ladakh": "18",
    "Lakshadweep": "19",
    "Madhya Pradesh": "20",
    "Maharashtra": "21",
    "Manipur": "22",
    "Meghalaya": "23",
    "Mizoram": "24",
    "Nagaland": "25",
    "Odisha": "26",
    "Puducherry": "27",
    "Punjab": "28",
    "Rajasthan": "29",
    "Sikkim": "30",
    "Tamil Nadu": "31",
    "Telangana": "32",
    "Tripura": "33",
    "Uttar Pradesh": "34",
    "Uttarakhand": "35",
    "West Bengal": "36"
}

BANKAUCTIONS_STATE_IDS = {
    "Andaman and Nicobar Islands": "36",
    "Andhra Pradesh": "1",
    "Arunachal Pradesh": "2",
    "Assam": "3",
    "Bihar": "4",
    "Chandigarh": "31",
    "Chhattisgarh": "5",
    "Dadra and Nagar Haveli and Daman and Diu": "37",
    "Delhi": "29",
    "Goa": "6",
    "Gujarat": "7",
    "Haryana": "8",
    "Himachal Pradesh": "9",
    "Jammu and Kashmir": "10",
    "Jharkhand": "11",
    "Karnataka": "12",
    "Kerala": "13",
    "Ladakh": "38",
    "Lakshadweep": "39",
    "Madhya Pradesh": "14",
    "Maharashtra": "15",
    "Manipur": "16",
    "Meghalaya": "17",
    "Mizoram": "18",
    "Nagaland": "19",
    "Odisha": "20",
    "Puducherry": "35",
    "Punjab": "21",
    "Rajasthan": "22",
    "Sikkim": "23",
    "Tamil Nadu": "24",
    "Telangana": "30",
    "Tripura": "25",
    "Uttar Pradesh": "26",
    "Uttarakhand": "27",
    "West Bengal": "28"
}

# Property types to filter
PROPERTY_TYPES = [
    "Flat",
    "Commercial Property",
    "Land and Building",
    "Land",
    "Commercial Shop"
]
